### ISSUE TITLE
Version 6.0 shows up not found

### ISSUE THREAD

**Issue by drewstone** [ethcore/jsonrpc-http-server#24]
Should a new update be pushed or is this number simply a placeholder for what should be `3.0.1`?

```
Updating registry `https://github.com/rust-lang/crates.io-index`
no matching package named `jsonrpc-http-server` found (required by `eth_rpc`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^6.0
versions found: 3.0.1, 3.0.0, 2.1.0, ..
```

Compiling from source and adding a dependency path also leads to compile errors with `mio`.

**Comment by debris** [comment]
Versions above `3.0` were not published to crates.io, cause we are using custom version hyper. We may switch to official version, but it will require some work.

> Compiling from source and adding a dependency path also leads to compile errors with `mio`.

What compile errors? I cannot reproduce them

**Comment by drewstone** [comment]
No worries, just needed to update rust. Thanks for the info.
